version: '3.9-alpine'

services:
  postgres:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MAX_CONNECTIONS: 500
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} "]
      interval: 5s
      timeout: 5s
      retries: 5  
    ports:
      - "5432:5432"
    networks:
      - wallet-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wallet-network
    environment:
      - APP_PORT=8080
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
  

networks:
  wallet-network:
    driver: bridge

volumes:
  pgdata:
